version: '3'
services:
  contact_service:
    build:
      context: ./contact_service
      dockerfile: Dockerfile
    image: contact_service:latest
    container_name: contact_service
    ports:
      - "8000:8000"
    volumes:
      - ./contact_service/src:/app/src